Refactoring

diff --git a/mmv b/mmv
--- a/mmv
+++ b/mmv
@@ -24,25 +24,26 @@ rename() {
 	done
 }
 
-# main procedure
-mmv() {
-	tmp=$(mktemp -d /tmp/mmvXXX) || return
-	trap cleanup EXIT
-	printf '%s\n' "$@" | tee "$tmp/old" >"$tmp/new"
-	[ "$EDITOR" ] || {
-		err 'EDITOR variable is not set'
-		return 1
-	}
-	$EDITOR "$tmp/new" || return
-	cmplc "$tmp/old" "$tmp/new" || {
-		err 'different line count'
-		return 1
-	}
-	paste -d '\n' "$tmp/old" "$tmp/new" | rename
-}
-
 [ $# -gt 0 ] || {
-	err 'usage: mmv FILES...'
+	echo 'usage: mmv FILES...'
 	exit
 }
-mmv "$@"
+[ "$EDITOR" ] || {
+	err 'EDITOR variable is not set'
+	exit 1
+}
+tmp=$(mktemp -d /tmp/mmvXXX) || {
+	err 'failed to create temporary directory'
+	exit 1
+}
+trap cleanup EXIT
+printf '%s\n' "$@" | tee "$tmp/old" >"$tmp/new"
+$EDITOR "$tmp/new" || {
+	err "$EDITOR terminated with code $?"
+	exit 1
+}
+cmplc "$tmp/old" "$tmp/new" || {
+	err 'different line count'
+	exit 1
+}
+paste -d '\n' "$tmp/old" "$tmp/new" | rename
